-- MySQL Script generated by MySQL Workbench
-- Thu Mar  8 04:42:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventory` ;

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory` DEFAULT CHARACTER SET utf8 ;
USE `inventory` ;

-- -----------------------------------------------------
-- Table `inventory`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`Location` ;

CREATE TABLE IF NOT EXISTS `inventory`.`Location` (
  `LocationId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LocationId`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`Store` ;

CREATE TABLE IF NOT EXISTS `inventory`.`Store` (
  `StoreId` INT NOT NULL AUTO_INCREMENT,
  `StoreType` SET('W', 'O') NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Location_LocationId` INT NOT NULL,
  PRIMARY KEY (`StoreId`),
  INDEX `fk_Store_Location1_idx` (`Location_LocationId` ASC),
  CONSTRAINT `fk_Store_Location1`
    FOREIGN KEY (`Location_LocationId`)
    REFERENCES `inventory`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`Size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`Size` ;

CREATE TABLE IF NOT EXISTS `inventory`.`Size` (
  `SizeId` INT NOT NULL AUTO_INCREMENT,
  `SizeName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`SizeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`Product` ;

CREATE TABLE IF NOT EXISTS `inventory`.`Product` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Size_SizeId` INT NOT NULL,
  `Store_StoreId` INT NULL,
  `InStock` INT NULL DEFAULT 0,
  `AvailableQuantity` INT NULL DEFAULT 0,
  `InTransit` INT NULL DEFAULT 0,
  `Type` SET('FP', 'C', 'PM') NULL,
  `MinimumOrderQuantity` INT NULL,
  `QuantityPerBox` INT NULL,
  `ReorderPoint` INT NULL,
  PRIMARY KEY (`ProductId`),
  INDEX `fk_Product_Store1_idx` (`Store_StoreId` ASC),
  INDEX `fk_Product_Size1_idx` (`Size_SizeId` ASC),
  CONSTRAINT `fk_Product_Store1`
    FOREIGN KEY (`Store_StoreId`)
    REFERENCES `inventory`.`Store` (`StoreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Size1`
    FOREIGN KEY (`Size_SizeId`)
    REFERENCES `inventory`.`Size` (`SizeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`Size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`Size` ;

CREATE TABLE IF NOT EXISTS `inventory`.`Size` (
  `SizeId` INT NOT NULL AUTO_INCREMENT,
  `SizeName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`SizeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`LocationRestriction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventory`.`LocationRestriction` ;

CREATE TABLE IF NOT EXISTS `inventory`.`LocationRestriction` (
  `Location_LocationId` INT NOT NULL,
  `Product_ProductId` INT NOT NULL,
  INDEX `fk_LocationRestriction_Location1_idx` (`Location_LocationId` ASC),
  PRIMARY KEY (`Location_LocationId`, `Product_ProductId`),
  INDEX `fk_LocationRestriction_Product1_idx` (`Product_ProductId` ASC),
  CONSTRAINT `fk_LocationRestriction_Location1`
    FOREIGN KEY (`Location_LocationId`)
    REFERENCES `inventory`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LocationRestriction_Product1`
    FOREIGN KEY (`Product_ProductId`)
    REFERENCES `inventory`.`Product` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
